name: Angular CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache npm modules and build artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ./dist
            ./node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json', '**/*.ts', '**/*.html', '**/*.scss') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install dependencies
        run: npm install

      - name: Install Chrome dependencies
        run: sudo apt-get install -y libnss3 fonts-liberation libfontconfig1 xorg xvfb gtk2-engines-pixbuf x11-apps

      - name: Start Xvfb
        run: |
          export DISPLAY=':99.0'
          Xvfb :99 -screen 0 1024x768x24 &

      - name: Run tests
        run: |
          export DISPLAY=':99.0'
          ng test --karma-config karma.conf.js --watch=false --browsers=ChromeHeadlessNoSandbox

      - name: Check system performance
        run: |
          uptime
          free -h
          df -h
          top -b -n 1
