name: Angular CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache npm modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Setup Headless Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libxss1 libappindicator1 libindicator7

      - name: Start Xvfb
        run: |
          Xvfb :99 -ac -screen 0 1280x1024x24 > /dev/null 2>&1 &

      - name: Run tests
        run: |
          export DISPLAY=:99
          Xvfb :99 -ac -screen 0 1280x1024x24 > /dev/null 2>&1 &
          xvfb_pid=$!
          npm test
          echo "Tests completed with status $?"
          kill $xvfb_pid || echo "Failed to kill Xvfb"
          ps -ef | grep Xvfb
